# Run this script with
# docker build -t lcaohoanq/swt301cd:1.0 -f Dockerfile-deployment .

FROM maven:3.9.9-eclipse-temurin-17-alpine AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml and source code
COPY pom.xml .
COPY src ./src

# Build the application, skipping tests
RUN mvn clean package -DskipTests

FROM tomcat:9.0-jdk17-temurin

# Remove the default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy the WAR file into the Tomcat webapps directory
COPY --from=build /app/target/SWT301_Test_Project-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
