services:
  tomcat-app:
    image: lcaohoanq/swt301cd:1.1 # Use the image from Docker Hub
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      DB_URL: jdbc:sqlserver://sqlserver:1433;databaseName=master
      DB_USERNAME: sa
      DB_PASSWORD: Luucaohoang1604^^
    networks:
      - cd_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Luucaohoang1604^^
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    networks:
      - cd_network
    volumes:
      - sqlserver-data:/var/opt/mssql

networks:
  cd_network:
    driver: bridge

volumes:
  sqlserver-data: