services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Luucaohoang1604^^"
      MSSQL_PID: Developer
    ports:
      - "1434:1433"
    networks:
      - cd_network
    volumes:
      - db_data:/var/opt/mssql
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile-deployment
    depends_on:
      - database
    networks:
      - cd_network
    ports:
      - "8080:8080"

volumes:
  db_data:

networks:
  cd_network: