services:
  mssql:
    image: lcaohoanq/swt301db:1.0
    container_name: ShopApp
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Luucaohoang1604^^
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mssql_network
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - mssql_network
    restart: unless-stopped

volumes:
  mssql_data:

networks:
  mssql_network:
    driver: bridge
