services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ShopApp
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Luucaohoang1604^^
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mssql_network

volumes:
  mssql_data:

networks:
  mssql_network:
    driver: bridge
