name: CI for Java Servlet App

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Set up a SQL Server Docker container
      mssql:
        image: lcaohoanq/swt301db:1.1
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 'Luucaohoang1604^^'
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        # Set up a wait time for the container to be ready
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Wait for SQL Server to be ready
        run: |
          echo "Waiting for SQL Server to start..."
          sleep 20
          echo "SQL Server is up and running."

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run Tests
        run: mvn test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: target/site/surefire-report.html
