name: CI for Java Servlet App

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Set up a SQL Server Docker container
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 'Luucaohoang1604^^'
        ports:
          - 1434:1433
        options: >-
          --health-cmd "exit 0" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Wait for SQL Server to be ready
        run: |
          echo "Waiting for SQL Server to start..."
          sleep 20
          echo "SQL Server is up and running."

      - name: Build and Test with Maven
        run: mvn -B clean test site

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Pandas and Openpyxl
        run: |
          pip install pandas
          pip install openpyxl

      - name: Convert XML to Excel
        run: python convert_xml_to_excel.py

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            target/site/surefire-report.html
            target/surefire-reports/test-report.xlsx
